name: Deploy to Vercel Production

on:
  push:
    branches: [monitorVercel]

env:
  VERCEL_ORG_ID: team_CAJvIQaSVQ7G5SczDUhmsBxU
  VERCEL_PROJECT_ID: prj_zSQlwW0PJqfFq7VZNf3OnI6fZLOK

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install --global vercel

      - name: Pull Vercel project info
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: kyros-app

      - name: Build
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: kyros-app

      - name: Deploy to production
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: kyros-app
